### ISSUE TITLE
Prepare Genesis Block for Mainnet

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/tomochain#224]
We should prepare Genesis Block for the mainnet before release 1.0.0.

To have genesis block, we need to finish the things relate to the genesis block:
- Chain configuration
- Addresses (foundation, multisig ...)
- Smart contracts
- Balances

**Comment by thanhson1085** [comment]
After discussing with the team, genesis will init:
- 55M TOMO for token holders
- 12M for team (8 years), will unlock 1.5M every year (Team MultiSig Wallet: 0x99)
- 16M for foundation (8 years), will unlock 2M every year (Foundation MultiSig Wallet: 0x68)
- First five masternodes will take 250K TOMO from Team MultiSig Wallet

**Comment by Logle** [comment]
The correct one is: 12M for team (4 years), will unlock 1.5M every 6 month (Team MultiSig Wallet: 0x99) @thanhson1085

**Comment by thanhson1085** [comment]
Updated, thanks for the correction
